// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz7KAyKeWve9dRNafG_-GQb0TCdSJbt30',
    appId: '1:1092366899385:android:95098449f6467ae40ea368',
    messagingSenderId: '1092366899385',
    projectId: 'pizza-polkowice',
    storageBucket: 'pizza-polkowice.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNH7xrauegki_vSTgL-Xd10fjJNTIdqmA',
    appId: '1:1092366899385:ios:879207a5662263240ea368',
    messagingSenderId: '1092366899385',
    projectId: 'pizza-polkowice',
    storageBucket: 'pizza-polkowice.appspot.com',
    iosClientId: '1092366899385-a5obcaa1d003t4ateg8sj4irfu2ijc0d.apps.googleusercontent.com',
    iosBundleId: 'com.piotrgnybek.pizzapolkowice',
  );
}
